name: grocery_accounting
description: "Grocery accounting app built with Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  cloud_firestore: ^6.10.0
  firebase_storage: ^13.6.0
  flutter_bloc: ^9.1.1
  get_it: ^9.3.0
  injectable: ^3.0.0
  equatable: ^3.0.0
  intl: ^0.20.3
  image_picker: ^1.2.3
  share_plus: ^13.3.0
  flutter_local_notifications: ^22.3.1
  google_mlkit_text_recognition: ^0.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  injectable_generator: ^3.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: CenturyGothic
      fonts:
        - asset: fonts/CenturyGothic.ttf
          style: normal
        - asset: fonts/CenturyGothicBold.ttf
          weight: 700
          style: normal
